apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: demo
spec:
  tracing:
  - providers:
    - name: zipkin
    randomSamplingPercentage: 100
    customTags:
      "Hatena Event":
        literal:
          value: "This's Zipkin Propagation  !!!!!!!!!"