apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sample
  namespace: observability
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      zipkin:
        endpoint: 0.0.0.0:9411

    processors:
      batch:    

    exporters:
      otlp:
        endpoint: jaeger-collector:4317
        tls:
          insecure: true

      debug:        

    service:
      pipelines:
        traces:
          receivers: [zipkin, otlp]
          processors: [batch]
          exporters: [debug, otlp]