apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server
  namespace: demo
  labels:
    app: python-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-server
  template:
    metadata:
      labels:
        app: python-server
    spec:
      containers:
        - name: python-server
          image: ghcr.io/keisukesakasai/work-2024/work-istio-tracing/python-server:auto-instrumented
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:  
            - name: CNDT_EASTERN_API_HOST
              value: "0.0.0.0"
            - name: CNDT_EASTERN_API_PORT
              value: "8080"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_HOST
              value: "mysql"
            - name: DB_NAME
              value: "population"
            - name: DB_PORT
              value: "3306"
            - name: FRUIT_SERVER_ADDRESS
              value: "http://query-fruit.demo.svc.cluster.local:8080"
            - name: OTEL_SERVICE_NAME
              value: python-server-auto-instrumented
            - name: OTEL_TRACES_EXPORTER
              value: zipkin
            - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
              value: "http://sample-collector.observability.svc.cluster.local:9411/api/v2/spans"              
            # - name: OTEL_EXPORTER_OTLP_PROTOCOL
            #   value: "http/protobuf"
            # - name: OTEL_EXPORTER_OTLP_ENDPOINT
            # value: "http://sample-collector.observability.svc.cluster.local:4318"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage,b3"
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 100Mi                
---
apiVersion: v1
kind: Service
metadata:
  name: python-server
  namespace: demo
spec:
  selector:
    app: python-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080              